/*
- Copyright (c) 2026 HaydenGuo
- Project: file-share-manager
- Gitee: https://gitee.com/ghl1024/file-share-manager
- GitHub: https://github.com/ghl1024/file-share-manager
- CNB: https://cnb.cool/ghl1024/file-share-manager
- GitCode: https://gitcode.com/haydenguo/file-share-manager
- Author: https://hayden.pub
 */

package router

import (
	"time"

	"file-share-manager/server/internal/handler"
	"file-share-manager/server/internal/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterRoutes(engine *gin.Engine) {
	authHandler := handler.NewAuthHandler()
	shareHandler := handler.NewShareHandler()

	v1 := engine.Group("/api/fileshare/v1")
	registerAuthRoutes(v1.Group("/auth"), authHandler)
	registerPublicShareRoutes(v1.Group("/share"), shareHandler)
	registerManagementRoutes(v1.Group("/management"), authHandler)
}

func registerPublicShareRoutes(group *gin.RouterGroup, shareHandler *handler.ShareHandler) {
	group.GET("/:token", middleware.RateLimitMiddleware(120, time.Minute), shareHandler.PublicInfo)
	group.POST("/:token/verify", middleware.RateLimitMiddleware(10, time.Minute), shareHandler.Verify)
	group.GET("/:token/download", middleware.RateLimitMiddleware(60, time.Minute), shareHandler.Download)
}

func registerAuthRoutes(group *gin.RouterGroup, authHandler *handler.AuthHandler) {
	group.POST("/login", middleware.RateLimitMiddleware(10, time.Minute), authHandler.Login)

	protected := group.Group("")
	protected.Use(middleware.AuthMiddleware(), middleware.AuditLogMiddleware())
	protected.POST("/logout", authHandler.Logout)
	protected.GET("/session", authHandler.Session)
	protected.GET("/profile", authHandler.Profile)
	protected.PUT("/profile", middleware.RateLimitMiddleware(30, time.Minute), authHandler.UpdateProfile)
	protected.PUT("/password", middleware.RateLimitMiddleware(5, 10*time.Minute), authHandler.ChangePassword)
	protected.GET("/workspaces", authHandler.Workspaces)
	protected.POST("/workspace/switch", authHandler.SwitchWorkspace)
}

func registerManagementRoutes(group *gin.RouterGroup, authHandler *handler.AuthHandler) {
	group.Use(middleware.AuthMiddleware(), middleware.AuditLogMiddleware())

	userNotificationHandler := handler.NewUserNotificationHandler()
	userNotifications := group.Group("/notifications")
	userNotifications.GET("", userNotificationHandler.List)
	userNotifications.GET("/unread-count", userNotificationHandler.UnreadCount)
	userNotifications.GET("/preferences", userNotificationHandler.Preferences)
	userNotifications.PUT("/preferences", userNotificationHandler.SavePreferences)
	userNotifications.PUT("/read-all", userNotificationHandler.MarkAllRead)
	userNotifications.PUT("/:id/read", userNotificationHandler.MarkRead)
	userNotifications.POST("/:id/open", userNotificationHandler.Open)

	users := group.Group("/system/users")
	users.Use(middleware.SuperAdminMiddleware())
	users.GET("", authHandler.ListUsers)
	users.GET("/:id", authHandler.GetUser)
	users.POST("", authHandler.CreateUser)
	users.PUT("/:id", authHandler.UpdateUser)
	users.DELETE("/:id", authHandler.DeleteUser)
	users.PUT("/:id/status", authHandler.UpdateUserStatus)
	users.PUT("/:id/password", authHandler.ResetUserPassword)

	workspaceHandler := handler.NewWorkspaceHandler()
	workspaces := group.Group("/workspaces")
	workspaces.POST("", middleware.SuperAdminMiddleware(), workspaceHandler.CreateWorkspace)
	workspaces.GET("", workspaceHandler.ListWorkspaces)
	workspaces.PUT("/:wid", middleware.SuperAdminMiddleware(), workspaceHandler.UpdateQuota)
	workspaces.POST("/:wid/members", workspaceHandler.AddMember)
	workspaces.GET("/:wid/members", workspaceHandler.ListMembers)
	workspaces.GET("/:wid/available-users", workspaceHandler.ListAvailableUsers)
	workspaces.PUT("/:wid/members/:uid/quota", workspaceHandler.UpdateMemberQuota)
	workspaces.DELETE("/:wid/members/:uid", workspaceHandler.RemoveMember)

	systemHandler := handler.NewSystemHandler()
	menuHandler := handler.NewMenuHandler()
	notificationHandler := handler.NewNotificationHandler()
	system := group.Group("/system")
	system.Use(middleware.SuperAdminMiddleware())
	system.GET("/configs", systemHandler.Config)
	system.GET("/permissions", handler.NewRoleHandler().ListPermissions)
	system.GET("/menus", menuHandler.List)
	system.GET("/menus/:id", menuHandler.Get)
	system.POST("/menus", menuHandler.Create)
	system.PUT("/menus/:id", menuHandler.Update)
	system.DELETE("/menus/:id", menuHandler.Delete)
	system.GET("/ldap", systemHandler.GetLDAP)
	system.POST("/ldap", systemHandler.SaveLDAP)
	system.POST("/ldap/test", systemHandler.LDAPTest)
	system.POST("/ldap/sync", systemHandler.LDAPManualSync)
	system.GET("/ldap/history", systemHandler.LDAPSyncHistory)
	system.GET("/clamav/health", systemHandler.ClamAVHealth)
	system.GET("/storage/health", systemHandler.StorageHealth)
	system.GET("/notifications", notificationHandler.ListChannels)
	system.POST("/notifications", notificationHandler.CreateChannel)
	system.GET("/notifications/outbox", notificationHandler.ListOutbox)
	system.POST("/notifications/outbox/:id/retry", notificationHandler.RetryOutbox)
	system.POST("/notifications/:id/test", middleware.RateLimitMiddleware(10, time.Minute), notificationHandler.TestChannel)
	system.PUT("/notifications/:id", notificationHandler.UpdateChannel)
	system.DELETE("/notifications/:id", notificationHandler.DeleteChannel)

	groupHandler := handler.NewGroupHandler()
	workspaces.POST("/:wid/groups", groupHandler.CreateGroup)
	workspaces.GET("/:wid/groups", groupHandler.ListGroups)
	workspaces.GET("/:wid/groups/directory", groupHandler.ListDirectory)
	workspaces.PUT("/:wid/groups/:gid", groupHandler.UpdateGroup)
	workspaces.GET("/:wid/groups/:gid/members", groupHandler.ListMembers)
	workspaces.DELETE("/:wid/groups/:gid", groupHandler.DeleteGroup)
	workspaces.POST("/:wid/groups/:gid/members", groupHandler.AddMemberToGroup)
	workspaces.DELETE("/:wid/groups/:gid/members/:uid", groupHandler.RemoveMember)

	data := group.Group("")
	data.Use(middleware.WorkspaceContextMiddleware())
	dashboardHandler := handler.NewDashboardHandler()
	data.GET("/dashboard/stats", dashboardHandler.Stats)
	nodeHandler := handler.NewNodeHandler()
	data.GET("/folders/roots", middleware.PermissionMiddleware("file:list"), nodeHandler.ListRoots)
	data.GET("/folders/:id/children", middleware.PermissionMiddleware("file:list"), nodeHandler.ListChildren)
	data.GET("/folders/tree", middleware.PermissionMiddleware("file:list"), nodeHandler.FolderTree)
	data.GET("/favorites", middleware.PermissionMiddleware("file:list"), nodeHandler.ListFavorites)
	collaborationHandler := handler.NewCollaborationHandler()
	data.GET("/collaboration/shared-with-me", middleware.PermissionMiddleware("file:list"), collaborationHandler.ListSharedWithMe)
	data.GET("/collaboration/recent", middleware.PermissionMiddleware("file:list"), collaborationHandler.ListRecent)
	data.POST("/folders", middleware.PermissionMiddleware("file:upload"), nodeHandler.CreateFolder)
	data.PUT("/folders/:id", middleware.PermissionMiddleware("file:upload"), nodeHandler.Rename)
	data.PUT("/nodes/:id", middleware.PermissionMiddleware("file:upload"), nodeHandler.Rename)
	data.PUT("/nodes/:id/favorite", middleware.PermissionMiddleware("file:list"), nodeHandler.SetFavorite)
	data.PUT("/nodes/batch/favorite", middleware.PermissionMiddleware("file:list"), nodeHandler.BatchFavorite)
	data.POST("/nodes/:id/move", middleware.PermissionMiddleware("file:upload"), nodeHandler.Move)
	data.POST("/nodes/batch/move", middleware.PermissionMiddleware("file:upload"), nodeHandler.BatchMove)
	data.DELETE("/nodes/:id", middleware.PermissionMiddleware("file:delete"), nodeHandler.Trash)
	data.POST("/nodes/batch/trash", middleware.PermissionMiddleware("file:delete"), nodeHandler.BatchTrash)
	data.POST("/nodes/:id/restore", middleware.PermissionMiddleware("file:restore"), nodeHandler.Restore)
	data.POST("/nodes/batch/restore", middleware.PermissionMiddleware("file:restore"), nodeHandler.BatchRestore)
	data.GET("/nodes/:id/detail", middleware.PermissionMiddleware("file:list"), nodeHandler.Detail)
	nodeCollaborationHandler := handler.NewNodeCollaborationHandler()
	data.GET("/nodes/:id/activity", middleware.PermissionMiddleware("file:list"), nodeCollaborationHandler.ListActivity)
	data.GET("/nodes/:id/comments", middleware.PermissionMiddleware("file:list"), nodeCollaborationHandler.ListComments)
	data.GET("/nodes/:id/mention-candidates", middleware.RateLimitMiddleware(120, time.Minute), middleware.PermissionMiddleware("file:list"), nodeCollaborationHandler.MentionCandidates)
	data.POST("/nodes/:id/comments", middleware.RateLimitMiddleware(30, time.Minute), middleware.PermissionMiddleware("file:list"), nodeCollaborationHandler.CreateComment)
	data.PUT("/nodes/:id/comments/:comment_id", middleware.RateLimitMiddleware(60, time.Minute), middleware.PermissionMiddleware("file:list"), nodeCollaborationHandler.UpdateComment)
	data.DELETE("/nodes/:id/comments/:comment_id", middleware.RateLimitMiddleware(30, time.Minute), middleware.PermissionMiddleware("file:list"), nodeCollaborationHandler.DeleteComment)
	data.GET("/trash", middleware.PermissionMiddleware("file:list"), nodeHandler.ListTrash)
	data.GET("/search", middleware.RateLimitMiddleware(30, time.Minute), middleware.PermissionMiddleware("file:list"), nodeHandler.Search)
	shareHandler := handler.NewShareHandler()
	data.POST("/shares", middleware.PermissionMiddleware("file:share:create"), shareHandler.Create)
	data.GET("/shares", middleware.PermissionMiddleware("file:share:create"), shareHandler.List)
	data.GET("/shares/:id", middleware.PermissionMiddleware("file:share:create"), shareHandler.Detail)
	data.POST("/shares/:id/revoke", middleware.PermissionMiddleware("file:share:create"), shareHandler.Revoke)
	fileHandler := handler.NewFileHandler()
	data.GET("/files/:id/versions", middleware.PermissionMiddleware("file:list"), fileHandler.ListVersions)
	data.POST("/files/:id/versions/:version/restore", middleware.PermissionMiddleware("file:restore"), fileHandler.RestoreVersion)
	data.POST("/files/:id/versions/:version/rescan", middleware.PermissionMiddleware("file:restore"), fileHandler.RescanVersion)
	data.GET("/files/:id/preview", middleware.PermissionMiddleware("file:download"), fileHandler.PreviewInfo)
	data.GET("/files/:id/preview/content", middleware.PermissionMiddleware("file:download"), fileHandler.PreviewContent)
	data.GET("/files/:id/download", middleware.PermissionMiddleware("file:download"), fileHandler.Download)
	batchDownloadHandler := handler.NewBatchDownloadHandler()
	data.POST("/batch-downloads", middleware.PermissionMiddleware("file:download"), batchDownloadHandler.Create)
	data.GET("/batch-downloads", middleware.PermissionMiddleware("file:download"), batchDownloadHandler.List)
	data.GET("/batch-downloads/:id", middleware.PermissionMiddleware("file:download"), batchDownloadHandler.Get)
	data.POST("/batch-downloads/:id/retry", middleware.PermissionMiddleware("file:download"), batchDownloadHandler.Retry)
	data.GET("/batch-downloads/:id/download", middleware.PermissionMiddleware("file:download"), batchDownloadHandler.Download)
	aclHandler := handler.NewACLHandler()
	data.GET("/folders/:id/acl", middleware.PermissionMiddleware("acl:manage"), aclHandler.List)
	data.PUT("/folders/:id/acl", middleware.PermissionMiddleware("acl:manage"), aclHandler.Replace)
	data.PUT("/folders/:id/inheritance", middleware.PermissionMiddleware("acl:manage"), aclHandler.SetInheritance)
	roleHandler := handler.NewRoleHandler()
	data.GET("/permissions", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.ListPermissions)
	data.GET("/roles", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.List)
	data.GET("/roles/:id", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.Get)
	data.POST("/roles", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.Create)
	data.PUT("/roles/:id", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.Update)
	data.DELETE("/roles/:id", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.Delete)
	data.PUT("/roles/:id/permissions", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.ReplacePermissions)
	data.PUT("/users/batch/roles", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.BatchAssignUserRoles)
	data.PUT("/users/:id/roles", middleware.PermissionMiddleware("workspace:role:manage"), roleHandler.AssignUserRoles)
	auditHandler := handler.NewAuditHandler()
	auditExportHandler := handler.NewAuditExportHandler()
	auditArchiveHandler := handler.NewAuditArchiveHandler()
	data.GET("/audit/logs", middleware.PermissionMiddleware("audit:list"), auditHandler.List)
	data.GET("/audit/events", middleware.PermissionMiddleware("audit:list"), auditHandler.List)
	data.GET("/audit/events/:id", middleware.PermissionMiddleware("audit:list"), auditHandler.Detail)
	data.GET("/audit/security-events", middleware.PermissionMiddleware("audit:list"), auditHandler.SecurityEvents)
	data.GET("/audit/policy", middleware.PermissionMiddleware("audit:list"), auditHandler.Policy)
	data.GET("/audit/streams/:workspace_id/verify", middleware.PermissionMiddleware("audit:list"), auditHandler.VerifyStream)
	data.POST("/audit/exports", middleware.PermissionMiddleware("audit:export"), auditExportHandler.Create)
	data.GET("/audit/exports", middleware.PermissionMiddleware("audit:export"), auditExportHandler.List)
	data.GET("/audit/exports/:id", middleware.PermissionMiddleware("audit:export"), auditExportHandler.Get)
	data.GET("/audit/exports/:id/download", middleware.PermissionMiddleware("audit:export"), auditExportHandler.Download)
	data.GET("/audit/archives", middleware.PermissionMiddleware("audit:list"), auditArchiveHandler.List)
	data.POST("/audit/archives/run", middleware.PermissionMiddleware("audit:archive"), auditArchiveHandler.Run)
	backupHandler := handler.NewBackupHandler()
	reconcileHandler := handler.NewReconcileHandler()
	data.GET("/backups", middleware.PermissionMiddleware("backup:manage"), backupHandler.List)
	data.GET("/backups/health", middleware.PermissionMiddleware("backup:manage"), backupHandler.Health)
	data.GET("/backup-restore-drills", middleware.PermissionMiddleware("backup:manage"), backupHandler.ListRestoreDrills)
	data.GET("/backups/:id", middleware.PermissionMiddleware("backup:manage"), backupHandler.Detail)
	data.POST("/backups/baseline", middleware.PermissionMiddleware("backup:manage"), backupHandler.CreateBaseline)
	data.POST("/backups/incremental", middleware.PermissionMiddleware("backup:manage"), backupHandler.CreateIncremental)
	data.POST("/backups/compact", middleware.PermissionMiddleware("backup:manage"), backupHandler.Compact)
	data.POST("/backups/:id/retry", middleware.PermissionMiddleware("backup:manage"), backupHandler.Retry)
	data.POST("/backups/:id/restore-drill", middleware.PermissionMiddleware("backup:manage"), backupHandler.RestoreDrill)
	data.POST("/backups/:id/verify", middleware.PermissionMiddleware("backup:manage"), backupHandler.Verify)
	data.POST("/backups/:id/restore", middleware.PermissionMiddleware("backup:manage"), backupHandler.Restore)
	data.POST("/backups/:id/restore-workspace", middleware.PermissionMiddleware("backup:manage"), middleware.SuperAdminMiddleware(), backupHandler.RestoreWorkspace)
	data.GET("/storage/reconcile", middleware.PermissionMiddleware("backup:manage"), reconcileHandler.Scan)
	data.POST("/storage/reconcile/quarantine", middleware.PermissionMiddleware("backup:manage"), reconcileHandler.Quarantine)
	uploadHandler := handler.NewUploadHandler()
	data.POST("/uploads/init", middleware.PermissionMiddleware("file:upload"), uploadHandler.Init)
	data.PUT("/uploads/:id/parts/:part_no", middleware.PermissionMiddleware("file:upload"), uploadHandler.Part)
	data.GET("/uploads/:id", middleware.PermissionMiddleware("file:upload"), uploadHandler.Status)
	data.GET("/uploads/:id/status", middleware.PermissionMiddleware("file:upload"), uploadHandler.Status)
	data.POST("/uploads/:id/complete", middleware.PermissionMiddleware("file:upload"), uploadHandler.Complete)
	data.DELETE("/uploads/:id", middleware.PermissionMiddleware("file:upload"), uploadHandler.Cancel)
}
